sudo: required
language: c
compiler:
- gcc
services:
- docker
script:
- git clone https://github.com/SpeciesFileGroup/taxonworks.git
- cd taxonworks
- docker-compose build
- echo "$DOCKER_PASSWORD" > docker login -u "$DOCKER_USERNAME" --password-stdin 
- docker images
- docker push jhpoelen/taxonworks_app:latest
- docker push jhpoelen/taxonworks_webpack:latest
