name: MacOS
on:
  push:
    branches:
      - test-instructions
jobs:
  install:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15] # [macos-11.0, macos-10.15] # Big Sur not available yet

    steps:
    - name: Install script
      run: |
        set -e
        curl -sSL https://get.rvm.io | bash
        source /Users/runner/.rvm/scripts/rvm
        rvm list
        brew install postgis
        brew install imagemagick
        brew install tesseract
        brew install node
        git clone https://github.com/SpeciesFileGroup/taxonworks.git
        cd taxonworks
        rvm install $(cat .ruby-version)
        cd .
        ruby -v
