name: MacOS
on:
  push:
    branches:
      - test-instructions
jobs:
  install:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15] # [macos-11.0, macos-10.15] # Big Sur not available yet

    steps:
    - name: Install script
      run: |
        set -x
        brew services list
        brew services restart -vvv postgresql
        createuser -s -d -w taxonworks_development # Replaced -P with -w since prompt cannot be answered in this context
        set -e
        curl -sSL https://get.rvm.io | bash
        source /Users/runner/.rvm/scripts/rvm
        set -x
        brew install postgis
        brew install imagemagick
        brew install tesseract
        brew install node
        git clone https://github.com/SpeciesFileGroup/taxonworks.git
        cd taxonworks
        set +x
        rvm install $(cat .ruby-version)
        set -x
        cd .
        ruby -v
        gem install bundler
        bundle
        npm install
        cp config/database.yml.example config/database.yml
        cp config/secrets.yml.example config/secrets.yml
        rake db:create
        rake db:migrate
        rake db:test:prepare
        rake db:seed:development project_id=1
        cp config/application_settings.yml.ci config/application_settings.yml
        rake
