name: MacOS
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 3 * * 6'
jobs:
  install:
    if: |
      (
        github.event_name == 'schedule' || github.event_name == 'pull_request' ||
        contains(github.event.head_commit.message, '[install all]') ||
        contains(github.event.head_commit.message, '[install macos]')
      )

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11, macos-10.15]

    steps:
    - name: Install script
      env:
        NO_COVERAGE_REPORT: 1
      run: |
        set -e
        set -x
        curl -sSL https://get.rvm.io | bash
        source /Users/runner/.rvm/scripts/rvm
        brew install postgis
        brew install proj # Force newer
        brew services restart postgresql
        brew install imagemagick
        brew install tesseract
        brew install node
        git clone https://github.com/SpeciesFileGroup/taxonworks.git
        cd taxonworks
        rvm install $(cat .ruby-version)
        cd .
        ruby -v
        gem install bundler
        bundle
        npm install
        createuser -s -d -w taxonworks_development # Replaced -P with -w since prompt cannot be answered in this context
        cp config/database.yml.example config/database.yml
        cp config/secrets.yml.example config/secrets.yml
        rake db:create
        rake db:migrate
        rake db:test:prepare
        rake db:seed:development project_id=1
        cp config/application_settings.yml.ci config/application_settings.yml
        rake
